environment:
  matrix:
    - RUBY_VERSION: "25-x64"

install:
  - appveyor DownloadFile https://imagemagick.org/download/binaries/ImageMagick-x86_64-pc-windows.exe
  - ImageMagick-x86_64-pc-windows.exe /VERYSILENT /TASKS=install_Devel /DIR="C:\ImageMagick-7"
  - SET PATH=C:\ImageMagick-7;C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - magick --version
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - rake -rdevkit
