language: ruby

cache:
  directories:
    - ~/.cache/rubocop_cache
    - vendor/bundle
    - build-ImageMagick

dist: xenial
addons:
  apt:
    packages:
      - build-essential
      - libx11-dev
      - libxext-dev
      - zlib1g-dev
      - liblcms2-dev
      - libpng-dev
      - libjpeg-dev
      - libfreetype6-dev
      - libxml2-dev
      - libtiff5-dev
      - libwebp-dev
      - ghostscript
      - ccache

os:
  - linux

sudo: required

env:
  - IMAGEMAGICK_VERSION=6.7.7-10
  - IMAGEMAGICK_VERSION=6.7.7-10 CONFIGURE_OPTIONS=--enable-hdri
  - IMAGEMAGICK_VERSION=6.8.9-10
  - IMAGEMAGICK_VERSION=6.8.9-10 CONFIGURE_OPTIONS=--enable-hdri
  - IMAGEMAGICK_VERSION=6.9.10-49
  - IMAGEMAGICK_VERSION=6.9.10-49 CONFIGURE_OPTIONS=--enable-hdri

before_install:
  - /bin/bash before_install_$TRAVIS_OS_NAME.sh

install: bundle install --path=vendor/bundle --verbose

rvm:
  - 2.3.8

matrix:
  include:
    - rvm: 2.3
      env: STYLE_CHECKS=true
