language: ruby

cache:
  directories:
    - ~/.ccache

os:
  - linux

sudo: required

env:
  - IMAGEMAGICK_VERSION=6.7.7-10

before_install:
  - source before_install_$TRAVIS_OS_NAME.sh

install: bundle install --verbose

rvm:
  - 2.3
