language: ruby

cache:
  directories:
    - ~/.ccache

os:
  - linux

sudo: required

env:
  - IMAGEMAGICK_VERSION=7.0.7-39
  - IMAGEMAGICK_VERSION=latest

before_install:
  - source before_install_$TRAVIS_OS_NAME.sh
  - magick -version

install: bundle install --verbose

script: rake

rvm:
  - 2.3
  - 2.5

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a98c1112f5d60f97a532
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
