name: CI

on: [push, pull_request]

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Ruby 2.3
  #     uses: eregon/use-ruby-action@master
  #     with:
  #       ruby-version: 2.3.8
  #   - name: Build and test with Rake
  #     run: |
  #       gem install bundler
  #       bundle install --jobs 4 --retry 3
  #       STYLE_CHECKS=true bundle exec rubocop

  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.3, 2.4, 2.5, 2.6, 2.7]
        imagemagick-version: [6.7.7-10, 6.8.9-10, 6.9.10-90, 7.0.9-20]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Update/Install packages
      run: |
        IMAGEMAGICK_VERSION=${{ matrix.imagemagick-version }} ./before_install_linux.sh
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby-version: [2.3.3, 2.4.9, 2.5.7, 2.6.5]
        imagemagick-version: [6.8.9-10, 6.9.10-90, 7.0.9-20]

    # https://github.com/actions/starter-workflows/issues/95
    # https://github.com/eine/setup-msys2/blob/master/.github/workflows/test.yml
    # https://github.com/eine/setup-msys2/blob/master/test.sh
    # https://github.com/numworks/setup-msys2/pull/6
    # https://github.com/acoustid/ffmpeg-build/pull/3
    # https://github.com/actions/virtual-environments/pull/342
    # https://github.com/actions/starter-workflows/tree/master/ci
    # https://github.com/actions/virtual-environments
    steps:
    - uses: actions/checkout@v2
    - name: Cache ImageMagick
      uses: actions/cache@v1
      with:
        path: ./build-ImageMagick
        key: v1-imagemagick-${{ matrix.imagemagick-version }}
        restore-keys: |
          v1-imagemagick-${{ matrix.imagemagick-version }}
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install ImageMagick
      run: |
        $imagemagick_version = "${{ matrix.imagemagick-version }}"
        $imagemagick_version_without_patch = $imagemagick_version.split("-")[0]
        $installer_name = "ImageMagick-$($imagemagick_version)-Q16-x64-dll.exe"
        $url = "https://ftp.icm.edu.pl/pub/graphics/ImageMagick/binaries/$($installer_name)"
        wget $url --progress=dot
        echo "before install"
        $result = Invoke-Expression "./$($installer_name) /VERYSILENT /TASKS=install_Devel"
        echo $result
        echo "after install"
        SET PATH="C:\Program Files\ImageMagick-$($imagemagick_version_without_patch)-Q16;%PATH%"
        bundle install --path=vendor/bundle --retry 3
    - name: Build and test with Rake
      run: |
        bundle exec rake
